env:
  global:
  - GH_REF: github.com/nhz-io/react-typo-component.git
  - secure: XR81l64AJZWvIduhGNh7JZipQeRIRqG5bIAu38nmrf0bQJAK70STtVQUMBcpMEKlRL2r06QYAzVD3OKtiq5TnLTHoMfCW+XhX5+KvZI+zs3P8gjGBkopHQWg0H9e29HjsryXCvK3/8//A2q5Akl2roGDXqiF/63cn4yqiF3fT6Liigxra/0pRmeEH6EUVVXaSJ9YkQ0CbDB0aw2k9boQALpwW3SrXUUavoY1LmZ58czc5dLiGXuN3kxplELVk2x/A+ZfjevGsRdHjR56+N/Pgs5+zfm/YBPqRQxDosVbtaO3n3AaAvL3sphJ5hmUN3ffWeWQBubNKSDdxataBm3Hg3TJvW/JttypzQhYMW7n1bkYaVuzAvsS2kapaE/5PTSAlmAPyC4f/egWskDpi1seDAlJ7KKmirxUglnw0xVCfmCLGIwCmIm8Z0crNXzap0Kxf8iv33zHFGgF/Kqf6C7Urheut1M0bsKNZFhmGoFt8nHaRRXDOPg60ZYRMfE2H7M8OZYdfCOsedvHUeh0Jl3fsivnmdt9S8n03gZ7QmTejoQht3+wGo+F6ZYN7KnIq/YXn6uRSY5TkVCyi2v2K7vc3MmTe0FGGqybEgEUB0gMuC5jrG0jC255t8C8ru9MTAB8RwJQQum/MfvN16WIusvODDK4njiZ8ipjBSGQ3r9zu6g=
language: node_js
node_js:
- '0.11'
- '0.12'
- iojs
- '4.2'
- '5.1'
script: npm run-script dist
deploy:
  provider: npm
  email: dev@nhz.io
  skip_cleanup: true
  api_key:
    secure: Gds4NviUcF/PbqDDsIN4IgldsVvt3rlKaQE3/JroJUANUMOrcyXpE3T8hrNmI9+qscQ7jRjGg4IEQh3pzf1Xg6LEkoe9BphQQy879cl74aRpiws9cvqbX0sFullK1dgaToiQlgnr4oibrF1ap9q4ZRonSM/9kkMISDHT+yeAVtigQ89Csg6hMjhkXOPFjxEebmpMJAXvRFH3GcFXRtEZLWG/aoQkxWgktWtIWamAfKTkF0pjxnx3bal0ZJqcW9OFYt/NZAWoCPrL2ngOs14+ImopZ1rzbP8IBCdP82w4j5QAik4znn8VBbLpFJOkEPhvLnrBF8TfmVLWY5N7bGSn7dsQrZ+OSIxod3M6MzgaU6oqJNWJtEdBrA20W+hhdJm8JoyzoXJU2VpMphr0UcW76fLEsOTtsKmqR9+DmsDHSPRgWujRybi9fP2AXGf7EmFlqlgWcRd4kfL/3P17tCVoB6PRx5tnyAEqz+q5TDl709AhptbmVChmTvBxfAANsHkwC1ZXWUxIR3I0CWhxHeMy4+xYRsvwf0qouOye9UvmCFdvqaJeWs0OefNVAf62ryyiF0na28vXDFJ4tIJK/HpFGbY2Wb3drbBKjRiZ6kB9JrZoUb2k+4g/ow3cAuYQf90MI1NmgfM+UpL1H5WXZHoxmZIg52g7ggnLb7S4j+FH6gY=
  on:
    repo: nhz-io/react-typo-component
    branch: master
after_deploy:
  - bash ./dev/gh-pages.sh
